version: '3'

services:
  web:
    build: ./web
    restart: always
    # expose:
    ports:
      - "8000:8000"
    links:
      - postgres:postgres
    volumes:
      - ./web:/usr/src/app
    depends_on:
      - postgres
    env_file: .env
    environment:
      DEBUG: 'true'
    command: gunicorn -b 0.0.0.0:8000 config.wsgi:application

  postgres:
    restart: always
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file: .env
    volumes:
      - pgdata:/var/lib/postgresql/data/

volumes:
  web:
  pgdata:
