# Generated by Django 3.0.8 on 2020-07-09 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='lot',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='auction.Lot'),
            preserve_default=False,
        ),
    ]
