# Generated by Django 3.0.8 on 2020-07-09 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_bid_lot'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='status',
            field=models.CharField(choices=[('AC', 'Active'), ('CD', 'Closed')], default='AC', max_length=2),
        ),
    ]
