# Generated by Django 3.0.8 on 2020-07-09 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_lot_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='status',
            field=models.CharField(choices=[('NW', 'New'), ('AC', 'Accepted')], default='NW', max_length=2),
        ),
    ]
