# Generated by Django 3.0.8 on 2020-07-09 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionuser',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=9, verbose_name='balance'),
        ),
    ]
